# Stores information on Lotus Mode 0x22 addresses - source https://github.com/Alcantor/LotusECU-T4e/tree/master/documentation/OBD/Lotus%20OBD%20Codes

# Data from Mode22-Info.csv [cite: 15]
mode22_info_data = [
    {'Address': '22 02 0E', 'Text': 'Serial Number', 'Response': '62 02 0E', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 0F', 'Text': 'Hardware Number', 'Response': '62 02 0F', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 10', 'Text': 'Cryptoflag', 'Response': '62 02 10', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 11', 'Text': 'ECU Type', 'Response': '62 02 11', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 1C', 'Text': 'ECU ID', 'Response': '62 02 1C', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 1D', 'Text': 'ECU ID', 'Response': '62 02 1D', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 1E', 'Text': 'ECU ID', 'Response': '62 02 1E', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 1F', 'Text': 'ECU ID', 'Response': '62 02 1F', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 21', 'Text': 'ECU ID', 'Response': '62 02 21', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 22', 'Text': 'ECU ID', 'Response': '62 02 22', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 23', 'Text': 'ECU ID', 'Response': '62 02 23', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 24', 'Text': 'ECU ID', 'Response': '62 02 24', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 63', 'Text': 'Variant Code', 'Response': '62 02 63', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'},
    {'Address': '22 02 64', 'Text': 'Variant Code', 'Response': '62 02 64', 'DataPos': '3', 'DataSize': '4', 'DataMask': '-1'}
]

# Data from Mode22-Live.csv [cite: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
# Note: Some multi-line entries in the original CSV were combined into single fields.
mode22_live_data = [
    {'Address': '22 02 01', 'Text': 'System Leak Status', 'Response': '62 02 01', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 02', 'Text': 'Purge DC', 'Response': '62 02 02', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.390625', 'TextUnit': '%'},
    {'Address': '22 02 03', 'Text': 'Idle Learn', 'Response': '62 02 03', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '9.77E-05', 'TextUnit': 'g/sec'},
    {'Address': '22 02 04', 'Text': 'Idle Air Output', 'Response': '62 02 04', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': 'g/sec'},
    {'Address': '22 02 05', 'Text': 'Injection Pulse Time (B1)', 'Response': '62 02 05', 'DataPos': '2', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'us'},
    {'Address': '22 02 06', 'Text': 'Idle Status', 'Response': '62 02 06', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 07', 'Text': 'VVT Target Cam Position (inlet)', 'Response': '62 02 07', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 08', 'Text': 'VVT Actual Cam Position (B1 inlet)', 'Response': '62 02 08', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 09', 'Text': 'VVL Status', 'Response': '62 02 09', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 0A', 'Text': 'Cat Diag Pre-Cat Sw B1', 'Response': '62 02 0A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 0B', 'Text': 'Cat Diag Pre-Cat Max Sw', 'Response': '62 02 0B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 0C', 'Text': 'Gear Position', 'Response': '62 02 0C', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 0D', 'Text': 'Idle Speed Target', 'Response': '62 02 0D', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '5', 'TextUnit': 'RPM'},
    {'Address': '22 02 12', 'Text': 'Purge Vacuum Pressure', 'Response': '62 02 12', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.1', 'TextUnit': 'mbar'},
    {'Address': '22 02 13', 'Text': 'Air Fuel Ratio Target', 'Response': '62 02 13', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': 'Ratio'},
    {'Address': '22 02 14', 'Text': 'Recirc Pump Relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '2', 'isSigned': 'FALSE', 'SimpleScale': '0.5', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'Fuel Pump Relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'Traction Contorl Status LED', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '32', 'isSigned': 'FALSE', 'SimpleScale': '0.03125', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'Cranking Relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '128', 'isSigned': 'FALSE', 'SimpleScale': '0.0078125', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'A/C Clutch Relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '16', 'isSigned': 'FALSE', 'SimpleScale': '0.0625', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'ACIS Intake Air Control', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '64', 'isSigned': 'FALSE', 'SimpleScale': '0.015625', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'Radiator Fan #2 relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '4', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': ''},
    {'Address': '22 02 14', 'Text': 'Radiator Fan #1 relay', 'Response': '62 02 14', 'DataPos': '0', 'DataSize': '1', 'DataMask': '8', 'isSigned': 'FALSE', 'SimpleScale': '0.125', 'TextUnit': ''},
    {'Address': '22 02 15', 'Text': 'Left front tyre pressure', 'Response': '62 02 15', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Right front tyre pressure', 'Response': '62 02 15', 'DataPos': '1', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Right rear tyre pressure', 'Response': '62 02 15', 'DataPos': '3', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Left front tyre pressure', 'Response': '62 02 15', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Right rear tyre pressure', 'Response': '62 02 15', 'DataPos': '3', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Right front tyre pressure', 'Response': '62 02 15', 'DataPos': '1', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Left rear tyre pressure', 'Response': '62 02 15', 'DataPos': '2', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 15', 'Text': 'Left rear tyre pressure', 'Response': '62 02 15', 'DataPos': '2', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.04', 'TextUnit': 'bar'},
    {'Address': '22 02 16', 'Text': 'Rear Right Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '128', 'isSigned': 'FALSE', 'SimpleScale': '0.0078125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Right Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '8', 'isSigned': 'FALSE', 'SimpleScale': '0.125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Right Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '8', 'isSigned': 'FALSE', 'SimpleScale': '0.125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Left Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '4', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Left Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '4', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Right Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '2', 'isSigned': 'FALSE', 'SimpleScale': '0.5', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Right Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '128', 'isSigned': 'FALSE', 'SimpleScale': '0.0078125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Left Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '64', 'isSigned': 'FALSE', 'SimpleScale': '0.015625', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Rear Left Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '64', 'isSigned': 'FALSE', 'SimpleScale': '0.015625', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Tyre Pressure Monitor System fault', 'Response': '62 02 16', 'DataPos': '0', 'DataSize': '1', 'DataMask': '256', 'isSigned': 'FALSE', 'SimpleScale': '0.00390625', 'TextUnit': ''}, # Potential typo in original DataMask (256 > 1 byte)
    {'Address': '22 02 16', 'Text': 'Front Right Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '2', 'isSigned': 'FALSE', 'SimpleScale': '0.5', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Tyre Pressure Monitor System fault', 'Response': '62 02 16', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Left Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '16', 'isSigned': 'FALSE', 'SimpleScale': '0.0625', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Right Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '32', 'isSigned': 'FALSE', 'SimpleScale': '0.03125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Left Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Right Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '32', 'isSigned': 'FALSE', 'SimpleScale': '0.03125', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Left Low Pressure', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '16', 'isSigned': 'FALSE', 'SimpleScale': '0.0625', 'TextUnit': ''},
    {'Address': '22 02 16', 'Text': 'Front Left Tyre Pressure Not Valid', 'Response': '62 02 16', 'DataPos': '1', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 17', 'Text': 'Injection Pulse Time (B2)', 'Response': '62 02 17', 'DataPos': '2', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'us'},
    {'Address': '22 02 18', 'Text': 'Octane Scaler Cylinder 1', 'Response': '62 02 18', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 19', 'Text': 'Octane Scaler Cylinder 3', 'Response': '62 02 19', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 1A', 'Text': 'Octane Scaler Cylinder 4', 'Response': '62 02 1A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 1B', 'Text': 'Octane Scaler Cylinder 2', 'Response': '62 02 1B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 25', 'Text': 'Ambient Air Temperature', 'Response': '62 02 25', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.625', 'TextUnit': 'degC'},
    {'Address': '22 02 26', 'Text': 'Mass Air Per Stroke', 'Response': '62 02 26', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '4', 'TextUnit': 'mg'},
    {'Address': '22 02 27', 'Text': 'Start-Up Coolant Temperature', 'Response': '62 02 27', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.625', 'TextUnit': 'degC'},
    {'Address': '22 02 28', 'Text': 'Accumulated Mass Air', 'Response': '62 02 28', 'DataPos': '0', 'DataSize': '4', 'DataMask': '-1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'mg'},
    {'Address': '22 02 29', 'Text': 'ECU Shutdown Timer', 'Response': '62 02 29', 'DataPos': '0', 'DataSize': '4', 'DataMask': '-1', 'isSigned': 'FALSE', 'SimpleScale': '0.005', 'TextUnit': 'Seconds'},
    {'Address': '22 02 2A', 'Text': 'Engine Load', 'Response': '62 02 2A', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': '%'},
    {'Address': '22 02 2B', 'Text': 'Cam Angle Error (B1 inlet)', 'Response': '62 02 2B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 2C', 'Text': 'Idle Speed Error', 'Response': '62 02 2C', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '1', 'TextUnit': 'RPM'},
    {'Address': '22 02 2D', 'Text': 'ECU On Timer', 'Response': '62 02 2D', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': 'Seconds'},
    {'Address': '22 02 2E', 'Text': 'Fuel Learn Dead Time (B1)', 'Response': '62 02 2E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '1', 'TextUnit': 'us'},
    {'Address': '22 02 2F', 'Text': 'Evaporative Vapour Concentration', 'Response': '62 02 2F', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '2', 'TextUnit': ''},
    {'Address': '22 02 30', 'Text': 'Cam Angle Error', 'Response': '62 02 30', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 31', 'Text': 'Knock Spark Advance Retard Cylinder 1', 'Response': '62 02 31', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 31', 'Text': 'Knock Spark Advance Retard Cylinder 3', 'Response': '62 02 31', 'DataPos': '2', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 31', 'Text': 'Knock Spark Advance Retard Cylinder 4', 'Response': '62 02 31', 'DataPos': '3', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 31', 'Text': 'Knock Spark Advance Retard Cylinder 2', 'Response': '62 02 31', 'DataPos': '1', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 32', 'Text': 'Idle Control Proportional Term', 'Response': '62 02 32', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.1', 'TextUnit': 'g/sec'},
    {'Address': '22 02 33', 'Text': 'Idle Control Integral Term', 'Response': '62 02 33', 'DataPos': '0', 'DataSize': '4', 'DataMask': '-1', 'isSigned': 'TRUE', 'SimpleScale': '9.77E-05', 'TextUnit': 'g/sec'},
    {'Address': '22 02 34', 'Text': 'Misfire Cylinder 1', 'Response': '62 02 34', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 35', 'Text': 'Misfire Cylinder 3', 'Response': '62 02 35', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 36', 'Text': 'Misfire Cylinder 4', 'Response': '62 02 36', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 37', 'Text': 'Misfire Cylinder 2', 'Response': '62 02 37', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 38', 'Text': 'Max Misfire Result (emissions)', 'Response': '62 02 38', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 39', 'Text': 'Max Misfire Result (cat damage)', 'Response': '62 02 39', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 3A', 'Text': 'Fuel Learn Timer', 'Response': '62 02 3A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': 'Seconds'},
    {'Address': '22 02 3B', 'Text': 'Throttle - Target Position', 'Response': '62 02 3B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.0977517', 'TextUnit': '%'},
    {'Address': '22 02 3C', 'Text': 'Idle Learn (AC on)', 'Response': '62 02 3C', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '9.77E-05', 'TextUnit': 'g/sec'},
    {'Address': '22 02 3D', 'Text': 'Wheel Speed - LR', 'Response': '62 02 3D', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': 'km/h'},
    {'Address': '22 02 3E', 'Text': 'Wheel Speed - RR', 'Response': '62 02 3E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': 'km/h'},
    {'Address': '22 02 3F', 'Text': 'Wheel Speed - LF', 'Response': '62 02 3F', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': 'km/h'},
    {'Address': '22 02 41', 'Text': 'Wheel Speed - RF', 'Response': '62 02 41', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': 'km/h'},
    {'Address': '22 02 42', 'Text': 'Traction Control - Slip', 'Response': '62 02 42', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 43', 'Text': 'Traction Control - Target Slip', 'Response': '62 02 43', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 44', 'Text': 'Pre-Cat O2 Diag Timer (B1)', 'Response': '62 02 44', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.005', 'TextUnit': 'Seconds'},
    {'Address': '22 02 45', 'Text': 'Throttle Position (0-100%)', 'Response': '62 02 45', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.0977517', 'TextUnit': '%'},
    {'Address': '22 02 46', 'Text': 'Pedal Position (0-100%)', 'Response': '62 02 46', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.0977517', 'TextUnit': '%'},
    {'Address': '22 02 47', 'Text': 'Evap Leak Check Result (0.040")', 'Response': '62 02 47', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.1', 'TextUnit': 'mbar'},
    {'Address': '22 02 48', 'Text': 'Fuel Learn Zone 2 (B1)', 'Response': '62 02 48', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.390625', 'TextUnit': '%'},
    {'Address': '22 02 49', 'Text': 'Fuel Learn Zone 3 (B1)', 'Response': '62 02 49', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.390625', 'TextUnit': '%'},
    {'Address': '22 02 4B', 'Text': 'VVT Actual Cam Position (B2 inlet)', 'Response': '62 02 4B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 4C', 'Text': 'Cat Diag Pre-Cat Sw B2', 'Response': '62 02 4C', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 4D', 'Text': 'Octane Scaler Cylinder 5', 'Response': '62 02 4D', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 4E', 'Text': 'Octane Scaler Cylinder 6', 'Response': '62 02 4E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001526', 'TextUnit': '%'},
    {'Address': '22 02 4F', 'Text': 'Cam Angle Error (B2 inlet)', 'Response': '62 02 4F', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 50', 'Text': 'VVT Actual Cam Position (B1 exhaust)', 'Response': '62 02 50', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 51', 'Text': 'VVT Actual Cam Position (B2 exhaust)', 'Response': '62 02 51', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 52', 'Text': 'VVT Target Cam Position (exhaust)', 'Response': '62 02 52', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 53', 'Text': 'Cam Angle Error (B1 exhaust)', 'Response': '62 02 53', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 54', 'Text': 'Cam Angle Error (B2 exhaust)', 'Response': '62 02 54', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 55', 'Text': 'Fuel Learn Dead Time (B2)', 'Response': '62 02 55', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '1', 'TextUnit': 'us'},
    {'Address': '22 02 56', 'Text': 'Knock Spark Advance Retard Cylinder 6', 'Response': '62 02 56', 'DataPos': '1', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 56', 'Text': 'Knock Spark Advance Retard Cylinder 5', 'Response': '62 02 56', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'degrees'},
    {'Address': '22 02 57', 'Text': 'Misfire Cylinder 5', 'Response': '62 02 57', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 58', 'Text': 'Misfire Cylinder 6', 'Response': '62 02 58', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 59', 'Text': 'Pre-Cat O2 Diag Timer (B2)', 'Response': '62 02 59', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.005', 'TextUnit': 'Seconds'},
    {'Address': '22 02 5A', 'Text': 'Fuel Learn Zone 2 (B2)', 'Response': '62 02 5A', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.390625', 'TextUnit': '%'},
    {'Address': '22 02 5B', 'Text': 'Fuel Learn Zone 3 (B2)', 'Response': '62 02 5B', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.390625', 'TextUnit': '%'},
    {'Address': '22 02 5C', 'Text': 'Traction Control Switch', 'Response': '62 02 5C', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 5D', 'Text': 'Sport Button', 'Response': '62 02 5D', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 5E', 'Text': 'Clutch Sensor', 'Response': '62 02 5E', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 5F', 'Text': 'Brake Switch (Upper)', 'Response': '62 02 5F', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 61', 'Text': 'Cruise Status', 'Response': '62 02 61', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 62', 'Text': 'A/C Evaporator Temperature', 'Response': '62 02 62', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': 'degrees'},
    {'Address': '22 02 65', 'Text': 'Brake Switch (Lower)', 'Response': '62 02 65', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 66', 'Text': 'ValveMatic Target Angle', 'Response': '62 02 66', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.009766', 'TextUnit': 'degrees'},
    {'Address': '22 02 67', 'Text': 'ValveMatic Actuator Angle', 'Response': '62 02 67', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.009766', 'TextUnit': 'degrees'},
    {'Address': '22 02 68', 'Text': 'Engine Bay Cooling Fan', 'Response': '62 02 68', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 69', 'Text': 'Clutch Sensor (Raw Data)', 'Response': '62 02 69', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 6A', 'Text': 'Engine Torque', 'Response': '62 02 6A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '1', 'TextUnit': 'Nm'},
    {'Address': '22 02 6B', 'Text': 'Cold Idle Learn', 'Response': '62 02 6B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '9.77E-05', 'TextUnit': 'g/sec'},
    {'Address': '22 02 6C', 'Text': 'Cold Idle Learn (AC on)', 'Response': '62 02 6C', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '9.77E-05', 'TextUnit': 'g/sec'},
    {'Address': '22 02 6D', 'Text': 'DPM Switch Position', 'Response': '62 02 6D', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 6E', 'Text': 'Exhaust Valve Override Switch Status', 'Response': '62 02 6E', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 6F', 'Text': 'Vehicle Mode', 'Response': '62 02 6F', 'DataPos': '0', 'DataSize': '1', 'DataMask': '7', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 70', 'Text': 'Paddle Shift Sensor (Raw Data)', 'Response': '62 02 70', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 71', 'Text': 'Dura Position Learn Status', 'Response': '62 02 71', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 72', 'Text': 'Manifold Temperature', 'Response': '62 02 72', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'degC'},
    {'Address': '22 02 73', 'Text': 'TCU sport switch status', 'Response': '62 02 73', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 75', 'Text': 'Oil Temperature', 'Response': '62 02 75', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'degC'},
    {'Address': '22 02 76', 'Text': 'Auto Gear', 'Response': '62 02 76', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 77', 'Text': 'Engine Speed (Received from ECU)', 'Response': '62 02 77', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': 'RPM'},
    {'Address': '22 02 78', 'Text': 'Gear Request', 'Response': '62 02 78', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 79', 'Text': 'Input Shaft Speed', 'Response': '62 02 79', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'RPM'},
    {'Address': '22 02 7A', 'Text': 'Output Shaft Speed', 'Response': '62 02 7A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'RPM'},
    {'Address': '22 02 7B', 'Text': 'SL1 Pressure Switch Status', 'Response': '62 02 7B', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 7C', 'Text': 'SL2 Pressure Switch Status', 'Response': '62 02 7C', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 7D', 'Text': 'SLU Pressure Switch Status', 'Response': '62 02 7D', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 7E', 'Text': 'Dura Position Sensor 1', 'Response': '62 02 7E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 7F', 'Text': 'Dura Position Sensor 2', 'Response': '62 02 7F', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 81', 'Text': 'Current Dura Position', 'Response': '62 02 81', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 82', 'Text': 'Learnt Dura Position Park', 'Response': '62 02 82', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 83', 'Text': 'Learnt Dura Position Reverse', 'Response': '62 02 83', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 84', 'Text': 'Learnt Dura Position Neutral', 'Response': '62 02 84', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 85', 'Text': 'Learnt Dura Position Drive', 'Response': '62 02 85', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.1', 'TextUnit': '%'},
    {'Address': '22 02 86', 'Text': 'PRND Feedback Switch status - Park', 'Response': '62 02 86', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 87', 'Text': 'PRND Feedback Switch status - Reverse', 'Response': '62 02 87', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 88', 'Text': 'PRND Feedback Switch status - Neutral', 'Response': '62 02 88', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 89', 'Text': 'PRND Feedback Switch status - Drive', 'Response': '62 02 89', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 8A', 'Text': 'Park Request Switch', 'Response': '62 02 8A', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 8B', 'Text': 'Reverse Request Switch', 'Response': '62 02 8B', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 8C', 'Text': 'Neutral Request Switch', 'Response': '62 02 8C', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 8D', 'Text': 'Drive Request Switch', 'Response': '62 02 8D', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 8E', 'Text': 'Gear Ratio', 'Response': '62 02 8E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '0.001', 'TextUnit': ''},
    {'Address': '22 02 8F', 'Text': 'Commanded Torque Converter Status', 'Response': '62 02 8F', 'DataPos': '0', 'DataSize': '1', 'DataMask': '3', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 90', 'Text': 'Green Learn Status', 'Response': '62 02 90', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 5 High Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '64', 'isSigned': 'FALSE', 'SimpleScale': '0.015625', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 6', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '128', 'isSigned': 'FALSE', 'SimpleScale': '0.0078125', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 4 High Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '16', 'isSigned': 'FALSE', 'SimpleScale': '0.0625', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 3 High Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '4', 'isSigned': 'FALSE', 'SimpleScale': '0.25', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 5 Low Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '32', 'isSigned': 'FALSE', 'SimpleScale': '0.03125', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 2', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '1', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 3 Low Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '2', 'isSigned': 'FALSE', 'SimpleScale': '0.5', 'TextUnit': ''},
    {'Address': '22 02 91', 'Text': 'Slip learn status flags - Gear 4 Low Index', 'Response': '62 02 91', 'DataPos': '0', 'DataSize': '1', 'DataMask': '8', 'isSigned': 'FALSE', 'SimpleScale': '0.125', 'TextUnit': ''},
    {'Address': '22 02 92', 'Text': 'Green Learn Target Load Minimum', 'Response': '62 02 92', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '2.588235', 'TextUnit': 'Nm'},
    {'Address': '22 02 93', 'Text': 'Green Learn Target Load Maximum', 'Response': '62 02 93', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '2.588235', 'TextUnit': 'Nm'},
    {'Address': '22 02 94', 'Text': 'Input Shaft Load', 'Response': '62 02 94', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '2.588235', 'TextUnit': 'Nm'},
    {'Address': '22 02 95', 'Text': 'Green Learn No. Complete current bin', 'Response': '62 02 95', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 96', 'Text': 'Green Learn Target No. current bin', 'Response': '62 02 96', 'DataPos': '0', 'DataSize': '1', 'DataMask': '255', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': ''},
    {'Address': '22 02 97', 'Text': 'Torque Converter Slip', 'Response': '62 02 97', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'FALSE', 'SimpleScale': '1', 'TextUnit': 'RPM'},
    {'Address': '22 02 98', 'Text': 'Solenoid SL Duty Cycle', 'Response': '62 02 98', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 99', 'Text': 'Solenoid SL1 Duty Cycle', 'Response': '62 02 99', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9A', 'Text': 'Solenoid SL2 Duty Cycle', 'Response': '62 02 9A', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9B', 'Text': 'Solenoid SL3 Duty Cycle', 'Response': '62 02 9B', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9C', 'Text': 'Solenoid SL4 Duty Cycle', 'Response': '62 02 9C', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9D', 'Text': 'Solenoid SLT Duty Cycle', 'Response': '62 02 9D', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9E', 'Text': 'Solenoid SLU Duty Cycle', 'Response': '62 02 9E', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 9F', 'Text': 'Solenoid SL Demand', 'Response': '62 02 9F', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A1', 'Text': 'Solenoid SL1 Demand', 'Response': '62 02 A1', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A2', 'Text': 'Solenoid SL2 Demand', 'Response': '62 02 A2', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A3', 'Text': 'Solenoid SL3 Demand', 'Response': '62 02 A3', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A4', 'Text': 'Solenoid SL4 Demand', 'Response': '62 02 A4', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A5', 'Text': 'Solenoid SLT Demand', 'Response': '62 02 A5', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'},
    {'Address': '22 02 A6', 'Text': 'Solenoid SLU Demand', 'Response': '62 02 A6', 'DataPos': '0', 'DataSize': '2', 'DataMask': '65535', 'isSigned': 'TRUE', 'SimpleScale': '0.01', 'TextUnit': '%'}
]